import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter, Outfit, Poppins } from "next/font/google";
import { ICProvider } from "@/providers/ICprovider";
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin", "latin-ext"],
  variable: "--font-inter",
});
const outfit = Outfit({
  subsets: ["latin", "latin-ext"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit",
});
const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-poppins",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${inter.variable} ${poppins.variable} ${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ICProvider>{children}</ICProvider>
        <Toaster/>
      </body>
    </html>
  );
}
